package cn.colams.dal.dao;

import cn.colams.dal.entity.WeightHistory;
import cn.colams.dal.entity.WeightHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeightHistoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    long countByExample(WeightHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int deleteByExample(WeightHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int insert(WeightHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int insertSelective(WeightHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    List<WeightHistory> selectByExampleWithRowbounds(WeightHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    List<WeightHistory> selectByExample(WeightHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    WeightHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeightHistory record, @Param("example") WeightHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeightHistory record, @Param("example") WeightHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeightHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeightHistory record);
}