package cn.colams.dal.dao;

import cn.colams.dal.entity.TicksEntity;
import cn.colams.dal.entity.TicksEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TicksEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    long countByExample(TicksEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int deleteByExample(TicksEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int insert(TicksEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int insertSelective(TicksEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    List<TicksEntity> selectByExampleWithRowbounds(TicksEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    List<TicksEntity> selectByExample(TicksEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    TicksEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TicksEntity record, @Param("example") TicksEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TicksEntity record, @Param("example") TicksEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TicksEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticks
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TicksEntity record);
}