package cn.colams.dal.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ticks
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TicksEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticks.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticks.tick
     *
     * @mbg.generated
     */
    private Date tick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticks.id
     *
     * @return the value of ticks.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticks.id
     *
     * @param id the value for ticks.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticks.tick
     *
     * @return the value of ticks.tick
     *
     * @mbg.generated
     */
    public Date getTick() {
        return tick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticks.tick
     *
     * @param tick the value for ticks.tick
     *
     * @mbg.generated
     */
    public void setTick(Date tick) {
        this.tick = tick;
    }
}