package cn.colams.dal.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   体重记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table weight_history
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class WeightHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_history.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_history.weight
     *
     * @mbg.generated
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_history.create_date
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_history.id
     *
     * @return the value of weight_history.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_history.id
     *
     * @param id the value for weight_history.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_history.weight
     *
     * @return the value of weight_history.weight
     *
     * @mbg.generated
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_history.weight
     *
     * @param weight the value for weight_history.weight
     *
     * @mbg.generated
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_history.create_date
     *
     * @return the value of weight_history.create_date
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_history.create_date
     *
     * @param createdate the value for weight_history.create_date
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}